import type { Question } from './types'

/**
 * Seed question bank modelled on the LTA Basic Theory Test syllabus.
 * Every question's scene must render the signs, lights and markings its stem
 * mentions; `lintQuestions` enforces this.
 */
export const questions: Question[] = [
  // ─── Traffic Signs ────────────────────────────────────────────────────────
  {
    id: 'signs-01',
    topic: 'signs',
    stem: 'You are approaching a junction with a {{give_way}} sign. What must you do?',
    options: ['Stop completely before the line, every time', 'Slow down and let traffic on the major road pass first', 'Proceed at normal speed if your lane is clear', 'Sound your horn and proceed'],
    answerIdx: 1,
    whyOneLiner: 'Give way means let others go first; a full stop is only needed if someone is coming.',
    scene: { road: 't_junction', signs: [{ id: 'give_way', side: 'left', depth: 0.4 }], markings: ['give_way_line'], vehicles: [{ kind: 'bus', pos: 'cross_right' }] },
    difficulty: 1,
  },
  {
    id: 'signs-02',
    topic: 'signs',
    stem: 'At a {{stop_sign}}, the road is completely clear in both directions. What should you do?',
    options: ['Slow down and proceed without stopping', 'Stop fully behind the stop line, then proceed when safe', 'Stop only if another vehicle is approaching', 'Flash your headlights and proceed'],
    answerIdx: 1,
    whyOneLiner: 'A stop sign always requires a complete stop, clear road or not.',
    scene: { road: 't_junction', signs: [{ id: 'stop', side: 'left', depth: 0.4 }], markings: ['stop_line'] },
    difficulty: 1,
  },
  {
    id: 'signs-03',
    topic: 'signs',
    stem: 'What does this {{no_entry}} sign mean?',
    options: ['No parking beyond this point', 'Road closed to all vehicles in this direction', 'No heavy vehicles', 'End of one-way street'],
    answerIdx: 1,
    whyOneLiner: 'Red disc with a white bar: you may not drive in from this side.',
    scene: { road: 'straight', signs: [{ id: 'no_entry', side: 'right', depth: 0.5 }, { id: 'no_entry', side: 'left', depth: 0.5 }] },
    difficulty: 1,
  },
  {
    id: 'signs-04',
    topic: 'signs',
    stem: 'You see a {{speed_limit}} sign showing 50. What does it mean?',
    options: ['You must drive at exactly 50 km/h', 'The minimum speed is 50 km/h', 'You must not exceed 50 km/h', 'The road is 50 m long'],
    answerIdx: 2,
    whyOneLiner: 'A red-ringed number is a maximum, not a target.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, signs: [{ id: 'speed_limit_50', side: 'left', depth: 0.5 }] },
    difficulty: 1,
  },
  {
    id: 'signs-05',
    topic: 'signs',
    stem: 'You want to turn back the way you came, but there is a {{no_u_turn}} sign. What should you do?',
    options: ['Make the U-turn if no traffic is coming', 'Continue and find a junction with a U-turn permitted sign', 'Make a three-point turn instead', 'Reverse into a side road and turn'],
    answerIdx: 1,
    whyOneLiner: 'In Singapore, U-turns are only allowed where a U-turn sign permits them.',
    scene: { road: 'cross_junction', light: 'green', signs: [{ id: 'no_u_turn', side: 'right', depth: 0.45 }], markings: ['stop_line'] },
    difficulty: 2,
  },
  {
    id: 'signs-06',
    topic: 'signs',
    stem: 'What does the {{keep_left}} sign tell you to do?',
    options: ['Turn left at the next junction', 'Pass the obstacle on its left side', 'Park on the left', 'Stay in the left lane for 1 km'],
    answerIdx: 1,
    whyOneLiner: 'Keep left is about which side of an island or obstruction to pass, not about turning.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, signs: [{ id: 'keep_left', side: 'right', depth: 0.5 }] },
    difficulty: 2,
  },
  {
    id: 'signs-07',
    topic: 'signs',
    stem: 'You see a {{road_hump}} sign. How should you drive?',
    options: ['Speed up to clear the hump quickly', 'Slow down before the hump and cross it gently', 'Move to the opposite lane to avoid it', 'Stop before the hump and check for traffic'],
    answerIdx: 1,
    whyOneLiner: 'Humps are there to slow you; slow before, not on, the hump.',
    scene: { road: 'straight', signs: [{ id: 'road_hump', side: 'left', depth: 0.5 }] },
    difficulty: 1,
  },
  {
    id: 'signs-08',
    topic: 'signs',
    stem: 'It is raining and you pass a {{slippery_road}} sign. What is the safest response?',
    options: ['Brake firmly to test your grip', 'Ease off the accelerator and avoid sudden steering or braking', 'Switch on hazard lights', 'Drive in the middle of the road'],
    answerIdx: 1,
    whyOneLiner: 'On a slippery surface, sudden inputs cause skids; be smooth.',
    scene: { road: 'bend', weather: 'rain', signs: [{ id: 'slippery_road', side: 'left', depth: 0.5 }], markings: ['double_white'] },
    difficulty: 2,
  },
  {
    id: 'signs-09',
    topic: 'signs',
    stem: 'You are in a {{school_zone}}. What speed and behaviour is expected?',
    options: ['50 km/h, normal driving', 'Slow to 40 km/h and watch for children stepping out', 'Stop and wait for a crossing guard', '30 km/h only during exam periods'],
    answerIdx: 1,
    whyOneLiner: 'School zones are 40 km/h and demand extra attention to pedestrians.',
    scene: { road: 'straight', signs: [{ id: 'school_zone', side: 'left', depth: 0.55 }], pedestrian: 'kerb_left', markings: ['zebra', 'zig_zag'] },
    difficulty: 1,
  },
  {
    id: 'signs-10',
    topic: 'signs',
    stem: 'A {{no_overtaking}} sign is in force and the lorry ahead is slow. What do you do?',
    options: ['Overtake when the oncoming lane is clear', 'Stay behind the lorry at a safe distance until the restriction ends', 'Overtake on the left', 'Sound your horn so the lorry pulls over'],
    answerIdx: 1,
    whyOneLiner: 'No overtaking means no overtaking, however slow the vehicle ahead.',
    scene: { road: 'bend', signs: [{ id: 'no_overtaking', side: 'left', depth: 0.45 }], markings: ['double_white'], vehicles: [{ kind: 'lorry', pos: 'ahead' }] },
    difficulty: 2,
  },

  // ─── Traffic Lights ───────────────────────────────────────────────────────
  {
    id: 'lights-01',
    topic: 'lights',
    stem: 'The light changes to {{traffic_light_amber}} as you approach the junction at normal speed. What should you do?',
    options: ['Accelerate to clear the junction before red', 'Stop at the stop line unless stopping would be unsafe', 'Continue at the same speed', 'Sound your horn and proceed'],
    answerIdx: 1,
    whyOneLiner: 'Amber means stop; only continue if you are too close to stop safely.',
    scene: { road: 'cross_junction', light: 'amber', markings: ['stop_line'] },
    difficulty: 1,
  },
  {
    id: 'lights-02',
    topic: 'lights',
    stem: 'The signal shows {{red_amber}} together. What does this mean?',
    options: ['Go, the light is about to turn green', 'Stay stopped; the light is about to change to green', 'Proceed with caution', 'The signal is faulty'],
    answerIdx: 1,
    whyOneLiner: 'Red-and-amber is still a stop signal; move off only on green.',
    scene: { road: 'cross_junction', light: 'red_amber', markings: ['stop_line'], vehicles: [{ kind: 'car', pos: 'cross_left' }] },
    difficulty: 1,
  },
  {
    id: 'lights-03',
    topic: 'lights',
    stem: 'The main light is red but a {{green_arrow}} pointing right is lit. You want to go straight. What do you do?',
    options: ['Go straight, the arrow means the junction is clear', 'Wait: the arrow only allows a right turn', 'Turn right instead', 'Sound horn and go straight'],
    answerIdx: 1,
    whyOneLiner: 'A filter arrow only releases traffic going in the arrow direction.',
    scene: { road: 'cross_junction', lanes: 2, egoLane: 1, light: 'green_arrow_right', markings: ['stop_line', 'arrow_right'] },
    difficulty: 2,
  },
  {
    id: 'lights-04',
    topic: 'lights',
    stem: 'The traffic light is showing {{flashing_amber}}. How should you treat this junction?',
    options: ['As a green light', 'Proceed with caution and give way to pedestrians and major-road traffic', 'As a red light: stop and wait for green', 'Reverse and find another route'],
    answerIdx: 1,
    whyOneLiner: 'Flashing amber means the signals are not controlling the junction; drive as if there were no lights.',
    scene: { road: 'cross_junction', light: 'flashing_amber', markings: ['give_way_line'], pedestrian: 'kerb_right' },
    difficulty: 2,
  },
  {
    id: 'lights-05',
    topic: 'lights',
    stem: 'The light is green but a pedestrian is still on the {{zebra_crossing}} in front of you. What do you do?',
    options: ['Proceed; green gives you right of way', 'Wait until the pedestrian has cleared your path', 'Sound your horn to hurry them', 'Drive around them slowly'],
    answerIdx: 1,
    whyOneLiner: 'A green light never overrides a pedestrian already crossing.',
    scene: { road: 'cross_junction', light: 'green', markings: ['zebra', 'stop_line'], pedestrian: 'crossing' },
    difficulty: 1,
  },
  {
    id: 'lights-06',
    topic: 'lights',
    stem: 'You are first in the {{filter_lane}} to turn right. The main light turns green but no arrow shows. Oncoming traffic is heavy. What do you do?',
    options: ['Turn immediately; green means go', 'Move into the junction and wait for a safe gap, giving way to oncoming traffic', 'Go straight instead', 'Reverse out of the filter lane'],
    answerIdx: 1,
    whyOneLiner: 'On a full green, right-turners give way to oncoming traffic; wait for a gap.',
    scene: { road: 'cross_junction', lanes: 3, egoLane: 3, light: 'green', markings: ['arrow_right', 'stop_line'], vehicles: [{ kind: 'car', pos: 'oncoming' }, { kind: 'motorcycle', pos: 'oncoming' }] },
    difficulty: 3,
  },

  // ─── Road Markings ────────────────────────────────────────────────────────
  {
    id: 'markings-01',
    topic: 'markings',
    stem: 'The road ahead has a yellow {{box_junction}}. The light is green but traffic beyond the box is not moving. What do you do?',
    options: ['Enter the box; green means go', 'Wait before the box until your exit is clear', 'Enter the box and stop inside until it clears', 'Use the opposite lane to pass'],
    answerIdx: 1,
    whyOneLiner: 'Never enter a box junction unless you can leave it without stopping inside.',
    scene: { road: 'cross_junction', light: 'green', markings: ['box_junction'], vehicles: [{ kind: 'car', pos: 'ahead' }, { kind: 'lorry', pos: 'ahead_far' }] },
    difficulty: 2,
  },
  {
    id: 'markings-02',
    topic: 'markings',
    stem: 'There is a {{double_white}} down the centre of the road and a slow lorry ahead. May you overtake?',
    options: ['Yes, if the road ahead is clear', 'No, you must not cross or straddle a double white line', 'Yes, but only on a straight section', 'Yes, if you signal first'],
    answerIdx: 1,
    whyOneLiner: 'Double white lines prohibit crossing; wait for them to end.',
    scene: { road: 'bend', markings: ['double_white'], vehicles: [{ kind: 'lorry', pos: 'ahead' }] },
    difficulty: 1,
  },
  {
    id: 'markings-03',
    topic: 'markings',
    stem: 'You want to drop a passenger off, but the kerb has a {{double_yellow_zigzag}}. Can you stop?',
    options: ['Yes, for under a minute', 'No, stopping is prohibited at all times here', 'Yes, if you keep the engine running', 'Only between 7am and 7pm'],
    answerIdx: 1,
    whyOneLiner: 'Double yellow zig-zags mean no stopping whatsoever.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, markings: ['double_yellow_zigzag'], pedestrian: 'kerb_left' },
    difficulty: 2,
  },
  {
    id: 'markings-04',
    topic: 'markings',
    stem: 'The kerb has a {{single_yellow}}. What is allowed?',
    options: ['Parking at any time', 'Brief stopping to drop off or pick up, but no parking during the hours shown', 'Nothing, no stopping at all', 'Parking only for taxis'],
    answerIdx: 1,
    whyOneLiner: 'A single yellow restricts parking, not a short stop.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, markings: ['single_yellow'] },
    difficulty: 2,
  },
  {
    id: 'markings-05',
    topic: 'markings',
    stem: 'You are approaching {{zig_zag_lines}} leading up to a {{zebra_crossing}}. What is not allowed on the zig-zags?',
    options: ['Driving over them', 'Stopping, parking or overtaking', 'Signalling', 'Slowing down'],
    answerIdx: 1,
    whyOneLiner: 'Zig-zags keep the approach to a crossing clear so pedestrians stay visible.',
    scene: { road: 'straight', markings: ['zebra', 'zig_zag'], pedestrian: 'kerb_right' },
    difficulty: 1,
  },
  {
    id: 'markings-06',
    topic: 'markings',
    stem: 'White {{chevron}} separate your lane from the slip road. May you drive across them to exit late?',
    options: ['Yes, chevrons are only advisory', 'No, do not drive on the chevrons; take the next exit instead', 'Yes, if you use hazard lights', 'Yes, at under 30 km/h'],
    answerIdx: 1,
    whyOneLiner: 'Chevron hatching separates streams of traffic; crossing it is dangerous and an offence.',
    scene: { road: 'expressway', lanes: 3, egoLane: 2, markings: ['chevron'], signs: [{ id: 'expressway_exit', side: 'left', depth: 0.35 }] },
    difficulty: 2,
  },
  {
    id: 'markings-07',
    topic: 'markings',
    stem: 'The centre of the road is a {{single_white_broken}}. What does it allow?',
    options: ['Nothing, treat it like a solid line', 'Crossing to overtake when it is safe to do so', 'Parking on either side', 'Driving on the line'],
    answerIdx: 1,
    whyOneLiner: 'Broken means "may cross with care"; solid means "do not cross".',
    scene: { road: 'straight', markings: ['single_white_broken'], vehicles: [{ kind: 'bicycle', pos: 'ahead' }] },
    difficulty: 1,
  },

  // ─── Junctions & Giving Way ───────────────────────────────────────────────
  {
    id: 'junctions-01',
    topic: 'junctions',
    stem: 'You are entering a {{roundabout}}. A car is already circulating and approaching from your right. What do you do?',
    options: ['Enter quickly before it reaches you', 'Give way to the car already on the roundabout', 'Sound your horn to claim priority', 'Stop on the roundabout and let it pass'],
    answerIdx: 1,
    whyOneLiner: 'Traffic already on the roundabout, coming from your right, has priority.',
    scene: { road: 'roundabout', signs: [{ id: 'roundabout_ahead', side: 'left', depth: 0.3 }], markings: ['give_way_line'], vehicles: [{ kind: 'car', pos: 'cross_right' }] },
    difficulty: 1,
  },
  {
    id: 'junctions-02',
    topic: 'junctions',
    stem: 'At an uncontrolled {{junction}} with no signs or lights, a car approaches on the road to your right. Who goes first?',
    options: ['You, because you arrived first', 'The car on your right', 'Whoever is faster', 'The larger vehicle'],
    answerIdx: 1,
    whyOneLiner: 'At an unmarked junction, give way to traffic from the right.',
    scene: { road: 'cross_junction', light: 'off', vehicles: [{ kind: 'car', pos: 'cross_right' }] },
    difficulty: 2,
  },
  {
    id: 'junctions-03',
    topic: 'junctions',
    stem: 'You are turning right at a {{junction}} on a green light. An oncoming car is going straight. Who has priority?',
    options: ['You, because you signalled first', 'The oncoming car going straight', 'Whoever reaches the centre first', 'Neither, both must stop'],
    answerIdx: 1,
    whyOneLiner: 'Vehicles turning across oncoming traffic must give way to it.',
    scene: { road: 'cross_junction', light: 'green', markings: ['stop_line'], vehicles: [{ kind: 'car', pos: 'oncoming' }], egoIndicator: 'right' },
    difficulty: 2,
  },
  {
    id: 'junctions-04',
    topic: 'junctions',
    stem: 'You are turning left at a junction. A pedestrian is waiting to cross the road you are turning into. What do you do?',
    options: ['Turn quickly before they step out', 'Give way to the pedestrian, then complete the turn', 'Sound your horn', 'Stop in the middle of the junction'],
    answerIdx: 1,
    whyOneLiner: 'Pedestrians crossing the road you are entering have priority.',
    scene: { road: 't_junction', markings: ['give_way_line'], pedestrian: 'kerb_left', egoIndicator: 'left' },
    difficulty: 1,
  },
  {
    id: 'junctions-05',
    topic: 'junctions',
    stem: 'An {{emergency_vehicle}} with siren is approaching from behind. What should you do?',
    options: ['Brake hard immediately', 'Signal and move aside safely to let it pass', 'Speed up to stay ahead of it', 'Follow closely behind it to get through traffic'],
    answerIdx: 1,
    whyOneLiner: 'Make room safely; never stop suddenly or tailgate the emergency vehicle.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, vehicles: [{ kind: 'ambulance', pos: 'behind_right', siren: true }], egoIndicator: 'left' },
    difficulty: 1,
  },
  {
    id: 'junctions-06',
    topic: 'junctions',
    stem: 'The car ahead has its {{hazard_lights}} on and is slowing. What does this most likely mean?',
    options: ['It is about to turn right', 'It is a hazard: broken down or stopping ahead', 'It is signalling you to overtake', 'Its indicators are faulty'],
    answerIdx: 1,
    whyOneLiner: 'Hazard lights warn of an obstruction, not a turn; keep your distance.',
    scene: { road: 'straight', lanes: 2, egoLane: 2, vehicles: [{ kind: 'car', pos: 'ahead', indicator: 'hazard' }] },
    difficulty: 1,
  },
  {
    id: 'junctions-07',
    topic: 'junctions',
    stem: 'When should you switch on your {{indicator}} before turning?',
    options: ['Just as you begin to steer', 'Early, before you slow down or move position', 'Only if other vehicles are present', 'After completing the turn'],
    answerIdx: 1,
    whyOneLiner: 'Signal early so others can react before you brake or steer.',
    scene: { road: 't_junction', markings: ['give_way_line'], vehicles: [{ kind: 'car', pos: 'ahead', indicator: 'left' }], egoIndicator: 'left' },
    difficulty: 1,
  },

  // ─── Expressways ──────────────────────────────────────────────────────────
  {
    id: 'expressway-01',
    topic: 'expressway',
    stem: 'You are on an {{expressway}} with no speed signs. What is the maximum speed?',
    options: ['70 km/h', '80 km/h', '90 km/h', '110 km/h'],
    answerIdx: 2,
    whyOneLiner: 'Expressways default to 90 km/h unless a lower limit is signed.',
    scene: { road: 'expressway', lanes: 3, egoLane: 2, vehicles: [{ kind: 'car', pos: 'ahead_far' }] },
    difficulty: 1,
  },
  {
    id: 'expressway-02',
    topic: 'expressway',
    stem: 'You want to leave the expressway at the {{slip_road}} ahead. What is the correct sequence?',
    options: ['Brake on the expressway, then signal and exit', 'Signal left early, move to the leftmost lane, exit, then slow down on the slip road', 'Cut across from the right lane when you see the exit', 'Stop on the shoulder and wait for a gap'],
    answerIdx: 1,
    whyOneLiner: 'Do your braking on the slip road, not in the fast-moving lane.',
    scene: { road: 'expressway', lanes: 3, egoLane: 1, signs: [{ id: 'expressway_exit', side: 'left', depth: 0.55 }], markings: ['chevron'], egoIndicator: 'left' },
    difficulty: 2,
  },
  {
    id: 'expressway-03',
    topic: 'expressway',
    stem: 'On an {{expressway}}, which lane should you normally drive in when not overtaking?',
    options: ['The rightmost lane', 'The leftmost lane that is free', 'The middle lane at all times', 'Any lane you like'],
    answerIdx: 1,
    whyOneLiner: 'Keep left; the right lane is for overtaking.',
    scene: { road: 'expressway', lanes: 3, egoLane: 1, vehicles: [{ kind: 'car', pos: 'right' }] },
    difficulty: 1,
  },
  {
    id: 'expressway-04',
    topic: 'expressway',
    stem: 'You are {{overtaking}} a lorry on the expressway. When may you move back to the left?',
    options: ['Immediately after your bonnet passes the lorry', 'When you can see the whole lorry in your rear-view mirror', 'When the lorry flashes its lights', 'Only at the next exit'],
    answerIdx: 1,
    whyOneLiner: 'Seeing the full vehicle in your mirror means you are clear of it.',
    scene: { road: 'expressway', lanes: 3, egoLane: 3, vehicles: [{ kind: 'lorry', pos: 'left' }], egoIndicator: 'left' },
    difficulty: 2,
  },
  {
    id: 'expressway-05',
    topic: 'expressway',
    stem: 'A {{speed_limit}} sign on the expressway shows 70 km/h ahead of roadworks. What does this mean for you?',
    options: ['Advisory only; 90 still applies', 'You must not exceed 70 km/h from that sign onward', 'Slow to 70 only if workers are visible', 'It applies only to heavy vehicles'],
    answerIdx: 1,
    whyOneLiner: 'A posted limit overrides the default expressway limit.',
    scene: { road: 'expressway', lanes: 3, egoLane: 2, signs: [{ id: 'speed_limit_70', side: 'left', depth: 0.6 }, { id: 'road_narrows', side: 'left', depth: 0.35 }] },
    difficulty: 2,
  },
  {
    id: 'expressway-06',
    topic: 'expressway',
    stem: 'Your car breaks down on the expressway. What should you do first?',
    options: ['Stand behind the car to warn traffic', 'Move onto the shoulder if possible, switch on hazard lights and place a warning triangle', 'Try to repair it in the lane', 'Flag down passing vehicles'],
    answerIdx: 1,
    whyOneLiner: 'Get out of live lanes and make yourself visible before anything else.',
    scene: { road: 'expressway', lanes: 3, egoLane: 1, egoIndicator: 'hazard', vehicles: [{ kind: 'car', pos: 'ahead_far' }] },
    difficulty: 1,
  },

  // ─── Stopping & Parking ───────────────────────────────────────────────────
  {
    id: 'parking-01',
    topic: 'parking',
    stem: 'You see a {{no_stopping}} sign. Your passenger just needs to hop out. Can you stop?',
    options: ['Yes, if it takes under 30 seconds', 'No, you may not stop here for any reason', 'Yes, with hazard lights on', 'Yes, outside peak hours'],
    answerIdx: 1,
    whyOneLiner: 'No stopping means exactly that: not even a brief pause.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, signs: [{ id: 'no_stopping', side: 'left', depth: 0.45 }], markings: ['double_yellow_zigzag'] },
    difficulty: 1,
  },
  {
    id: 'parking-02',
    topic: 'parking',
    stem: 'What does a {{no_waiting}} sign allow you to do?',
    options: ['Park for up to 15 minutes', 'Stop briefly to pick up or drop off passengers, but not wait', 'Nothing; it is the same as no stopping', 'Wait with the engine running'],
    answerIdx: 1,
    whyOneLiner: 'One slash allows a quick stop; two slashes (no stopping) allow nothing.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, signs: [{ id: 'no_waiting', side: 'left', depth: 0.45 }], markings: ['single_yellow'] },
    difficulty: 2,
  },
  {
    id: 'parking-03',
    topic: 'parking',
    stem: 'How close to a {{zebra_crossing}} may you park?',
    options: ['Right up to the stripes', 'Not on the zig-zag lines on either side of it', 'Within 3 metres', 'Anywhere if you use hazard lights'],
    answerIdx: 1,
    whyOneLiner: 'Parking near a crossing hides pedestrians from drivers.',
    scene: { road: 'straight', markings: ['zebra', 'zig_zag'] },
    difficulty: 1,
  },
  {
    id: 'parking-04',
    topic: 'parking',
    stem: 'You are on a {{one_way}} street. Which side may you park on?',
    options: ['Left side only', 'Right side only', 'Either side, unless signs or markings say otherwise', 'Neither side'],
    answerIdx: 2,
    whyOneLiner: 'On a one-way street, both kerbs are available unless restricted.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, signs: [{ id: 'one_way', side: 'right', depth: 0.5 }] },
    difficulty: 2,
  },
  {
    id: 'parking-05',
    topic: 'parking',
    stem: 'A {{bus_lane}} is in operation. When may a car enter it?',
    options: ['Whenever it is empty', 'Only to turn left at the next junction, or when the operating hours have ended', 'To overtake slow traffic', 'Never, at any time'],
    answerIdx: 1,
    whyOneLiner: 'Bus lanes are for buses in operating hours; cars may cross to turn left.',
    scene: { road: 'straight', lanes: 2, egoLane: 2, signs: [{ id: 'bus_lane', side: 'left', depth: 0.5 }], markings: ['bus_lane_marking'], vehicles: [{ kind: 'bus', pos: 'left' }] },
    difficulty: 2,
  },
  {
    id: 'parking-06',
    topic: 'parking',
    stem: 'Before opening your door after parking at the kerb, what should you do?',
    options: ['Switch on hazard lights', 'Check mirrors and look over your shoulder for cyclists and traffic', 'Sound the horn', 'Open it quickly to avoid blocking traffic'],
    answerIdx: 1,
    whyOneLiner: 'A door opened into a cyclist is a common, avoidable crash.',
    scene: { road: 'straight', lanes: 2, egoLane: 1, vehicles: [{ kind: 'bicycle', pos: 'behind_right' }], timeOfDay: 'dusk' },
    difficulty: 1,
  },
]

export const questionById = new Map(questions.map((q) => [q.id, q]))
export const questionsByTopic = (topicId: string) => questions.filter((q) => q.topic === topicId)
