import type { Term } from './types'

/**
 * Seed glossary modelled on the Singapore Highway Code / LTA Basic Theory
 * syllabus. Replace or extend with the official bank when available.
 */
export const terms: Term[] = [
  {
    id: 'give_way',
    name: 'give way',
    category: 'sign',
    visual: { sign: 'give_way' },
    plainMeaning: "Let others go first. You don't have to stop if the road is clear.",
    pair: {
      yes: {
        caption: 'Giving way: you slow and let the bus through first.',
        scene: { road: 't_junction', signs: [{ id: 'give_way', side: 'left', depth: 0.35 }], markings: ['give_way_line'], vehicles: [{ kind: 'bus', pos: 'cross_right' }] },
      },
      no: {
        caption: 'Not giving way: pulling out in front of the bus.',
        scene: { road: 't_junction', signs: [{ id: 'give_way', side: 'left', depth: 0.35 }], markings: ['give_way_line'], vehicles: [{ kind: 'bus', pos: 'cross_right' }], egoIndicator: 'right' },
      },
    },
    confusables: ['stop_sign', 'junction'],
  },
  {
    id: 'stop_sign',
    name: 'stop sign',
    category: 'sign',
    visual: { sign: 'stop' },
    plainMeaning: 'Come to a complete stop at the line, every time, even if nothing is coming.',
    pair: {
      yes: { caption: 'Stopped fully at the stop line before moving off.', scene: { road: 't_junction', signs: [{ id: 'stop', side: 'left', depth: 0.35 }], markings: ['stop_line'] } },
      no: { caption: 'Rolling through slowly because the road looks clear.', scene: { road: 't_junction', signs: [{ id: 'stop', side: 'left', depth: 0.35 }], markings: ['stop_line'], vehicles: [{ kind: 'car', pos: 'cross_left' }] } },
    },
    confusables: ['give_way', 'stop_line'],
  },
  {
    id: 'stop_line',
    name: 'stop line',
    category: 'marking',
    visual: { marking: 'stop_line' },
    plainMeaning: 'The thick solid white line across your lane. Your front wheels stop behind it, not on it.',
    confusables: ['give_way_line', 'stop_sign'],
  },
  {
    id: 'give_way_line',
    name: 'give way line',
    category: 'marking',
    visual: { marking: 'give_way_line' },
    plainMeaning: 'Broken white line across the lane mouth. Slow down and let crossing traffic pass; stop only if needed.',
    confusables: ['stop_line', 'give_way'],
  },
  {
    id: 'junction',
    name: 'junction',
    category: 'place',
    visual: { scene: { road: 'cross_junction', light: 'off' } },
    plainMeaning: 'Where two or more roads meet. T-junctions, crossroads and roundabouts are all junctions.',
    confusables: ['give_way', 'box_junction'],
  },
  {
    id: 'box_junction',
    name: 'box junction',
    category: 'marking',
    visual: { marking: 'box_junction' },
    plainMeaning: 'Yellow criss-cross grid. Do not enter unless your exit is clear, so you never get stuck blocking it.',
    pair: {
      yes: { caption: 'Waiting before the box because the exit is blocked.', scene: { road: 'cross_junction', markings: ['box_junction'], light: 'green', vehicles: [{ kind: 'car', pos: 'ahead' }, { kind: 'lorry', pos: 'ahead_far' }] } },
      no: { caption: 'Stopped inside the box, blocking cross traffic.', scene: { road: 'cross_junction', markings: ['box_junction'], light: 'red', vehicles: [{ kind: 'car', pos: 'cross_left' }] } },
    },
    confusables: ['junction', 'zig_zag_lines'],
  },
  {
    id: 'zebra_crossing',
    name: 'zebra crossing',
    category: 'marking',
    visual: { marking: 'zebra' },
    plainMeaning: 'Black-and-white striped pedestrian crossing. Pedestrians have right of way once they step on it.',
    pair: {
      yes: { caption: 'Stopping for the pedestrian waiting at the kerb.', scene: { road: 'straight', markings: ['zebra', 'zig_zag'], pedestrian: 'kerb_left' } },
      no: { caption: 'Driving through while a pedestrian is crossing.', scene: { road: 'straight', markings: ['zebra', 'zig_zag'], pedestrian: 'crossing' } },
    },
    confusables: ['zig_zag_lines', 'pedestrian_crossing_sign'],
  },
  {
    id: 'pedestrian_crossing_sign',
    name: 'pedestrian crossing ahead sign',
    category: 'sign',
    visual: { sign: 'zebra_ahead' },
    plainMeaning: 'Warning triangle: a zebra crossing is coming up. Slow down and look for people waiting.',
    confusables: ['zebra_crossing', 'school_zone'],
  },
  {
    id: 'zig_zag_lines',
    name: 'zig-zag lines',
    category: 'marking',
    visual: { marking: 'zig_zag' },
    plainMeaning: 'White zig-zags on either side of a zebra crossing. No stopping, parking or overtaking on them.',
    confusables: ['zebra_crossing', 'double_yellow_zigzag'],
  },
  {
    id: 'double_yellow_zigzag',
    name: 'double yellow zig-zag',
    category: 'marking',
    visual: { marking: 'double_yellow_zigzag' },
    plainMeaning: 'Yellow zig-zags along the kerb: no stopping at any time, not even to drop someone off.',
    confusables: ['zig_zag_lines', 'no_stopping', 'single_yellow'],
  },
  {
    id: 'single_yellow',
    name: 'single yellow line',
    category: 'marking',
    visual: { marking: 'single_yellow' },
    plainMeaning: 'Continuous yellow line along the kerb: no parking during the hours shown, but brief stopping to drop off is allowed.',
    confusables: ['double_yellow_zigzag', 'no_waiting'],
  },
  {
    id: 'double_white',
    name: 'double white line',
    category: 'marking',
    visual: { marking: 'double_white' },
    plainMeaning: 'Two solid white lines down the middle. Do not cross or straddle them, no overtaking.',
    pair: {
      yes: { caption: 'Staying in lane behind the lorry.', scene: { road: 'bend', markings: ['double_white'], vehicles: [{ kind: 'lorry', pos: 'ahead' }] } },
      no: { caption: 'Crossing the double white to overtake on a bend.', scene: { road: 'bend', markings: ['double_white'], vehicles: [{ kind: 'lorry', pos: 'ahead' }, { kind: 'car', pos: 'oncoming' }], egoIndicator: 'right' } },
    },
    confusables: ['single_white_broken', 'overtaking'],
  },
  {
    id: 'single_white_broken',
    name: 'broken white line',
    category: 'marking',
    visual: { marking: 'single_white_broken' },
    plainMeaning: 'Dashed white centre line. You may cross it to overtake when it is safe.',
    confusables: ['double_white'],
  },
  {
    id: 'chevron',
    name: 'chevron markings',
    category: 'marking',
    visual: { marking: 'chevron' },
    plainMeaning: 'White arrow-shaped hatching separating traffic streams. Do not drive on it unless it is broken-edged and safe.',
    confusables: ['expressway_exit'],
  },
  {
    id: 'overtaking',
    name: 'overtaking',
    category: 'rule',
    visual: { scene: { road: 'straight', lanes: 2, egoLane: 1, markings: ['single_white_broken'], vehicles: [{ kind: 'lorry', pos: 'ahead' }] } },
    plainMeaning: 'Passing a slower vehicle ahead. In Singapore you overtake on the right, when the road ahead is clear.',
    confusables: ['double_white', 'keep_left'],
  },
  {
    id: 'keep_left',
    name: 'keep left',
    category: 'sign',
    visual: { sign: 'keep_left' },
    plainMeaning: 'Blue circle with a downward-left arrow: pass this obstacle or island on its left side.',
    confusables: ['turn_left_ahead', 'one_way'],
  },
  {
    id: 'turn_left_ahead',
    name: 'turn left ahead',
    category: 'sign',
    visual: { sign: 'turn_left_ahead' },
    plainMeaning: 'Blue circle with a curved arrow: you must turn left at the junction ahead.',
    confusables: ['keep_left', 'no_right_turn'],
  },
  {
    id: 'one_way',
    name: 'one-way street',
    category: 'sign',
    visual: { sign: 'one_way' },
    plainMeaning: 'Blue rectangle with a white arrow: all traffic flows in that one direction.',
    confusables: ['no_entry', 'keep_left'],
  },
  {
    id: 'no_entry',
    name: 'no entry',
    category: 'sign',
    visual: { sign: 'no_entry' },
    plainMeaning: 'Red circle with a white bar: do not drive in. Usually the wrong end of a one-way street.',
    confusables: ['one_way', 'no_stopping'],
  },
  {
    id: 'speed_limit',
    name: 'speed limit',
    category: 'sign',
    visual: { sign: 'speed_limit_50' },
    plainMeaning: 'Red-ringed circle with a number: the maximum km/h on this road. Default is 50 km/h unless signed otherwise.',
    confusables: ['expressway'],
  },
  {
    id: 'no_u_turn',
    name: 'no U-turn',
    category: 'sign',
    visual: { sign: 'no_u_turn' },
    plainMeaning: 'Red-ringed circle with a crossed U arrow: turning back the way you came is not allowed here.',
    confusables: ['u_turn_permitted', 'no_right_turn'],
  },
  {
    id: 'u_turn_permitted',
    name: 'U-turn permitted',
    category: 'sign',
    visual: { sign: 'u_turn_permitted' },
    plainMeaning: 'Blue square with a U arrow. In Singapore you may only U-turn where this sign is present.',
    confusables: ['no_u_turn'],
  },
  {
    id: 'no_right_turn',
    name: 'no right turn',
    category: 'sign',
    visual: { sign: 'no_right_turn' },
    plainMeaning: 'Red-ringed circle with a crossed right arrow: you cannot turn right at this junction.',
    confusables: ['no_u_turn', 'turn_left_ahead'],
  },
  {
    id: 'traffic_light_amber',
    name: 'amber light',
    category: 'light',
    visual: { light: 'amber' },
    plainMeaning: 'Stop at the line, unless you are so close that stopping suddenly would be dangerous. It does not mean "hurry through".',
    pair: {
      yes: { caption: 'Braking smoothly to stop at the line on amber.', scene: { road: 'cross_junction', light: 'amber', markings: ['stop_line'] } },
      no: { caption: 'Speeding up to beat the red.', scene: { road: 'cross_junction', light: 'amber', markings: ['stop_line'], vehicles: [{ kind: 'car', pos: 'cross_right' }] } },
    },
    confusables: ['red_amber', 'flashing_amber'],
  },
  {
    id: 'red_amber',
    name: 'red and amber together',
    category: 'light',
    visual: { light: 'red_amber' },
    plainMeaning: 'Red with amber: about to turn green. Stay stopped and get ready, but do not move yet.',
    confusables: ['traffic_light_amber'],
  },
  {
    id: 'flashing_amber',
    name: 'flashing amber',
    category: 'light',
    visual: { light: 'flashing_amber' },
    plainMeaning: 'Signals are out of normal operation. Proceed with caution and give way to pedestrians and traffic on the major road.',
    confusables: ['traffic_light_amber'],
  },
  {
    id: 'green_arrow',
    name: 'green filter arrow',
    category: 'light',
    visual: { light: 'green_arrow_right' },
    plainMeaning: 'A green arrow lets you go in the direction shown, even if the main light is red. Only that direction.',
    pair: {
      yes: { caption: 'Turning right on the green arrow.', scene: { road: 'cross_junction', light: 'green_arrow_right', markings: ['arrow_right'], egoIndicator: 'right' } },
      no: { caption: 'Going straight on the arrow while the main light is red.', scene: { road: 'cross_junction', light: 'green_arrow_right', markings: ['arrow_right'], vehicles: [{ kind: 'car', pos: 'cross_left' }] } },
    },
    confusables: ['filter_lane', 'traffic_light_amber'],
  },
  {
    id: 'filter_lane',
    name: 'filter lane',
    category: 'place',
    visual: { scene: { road: 'cross_junction', lanes: 3, egoLane: 3, markings: ['arrow_right'], light: 'green_arrow_right' } },
    plainMeaning: 'A lane reserved for turning in one direction, usually marked with an arrow. Being in it commits you to that turn.',
    confusables: ['green_arrow', 'chevron'],
  },
  {
    id: 'expressway',
    name: 'expressway',
    category: 'place',
    visual: { scene: { road: 'expressway', lanes: 3, egoLane: 2, signs: [{ id: 'speed_limit_90', side: 'left', depth: 0.6 }] } },
    plainMeaning: 'A high-speed road with no junctions, only slip roads on and off (PIE, CTE, ECP...). Limit is 90 km/h unless signed lower.',
    confusables: ['slip_road', 'speed_limit'],
  },
  {
    id: 'slip_road',
    name: 'slip road (exit)',
    category: 'place',
    visual: { sign: 'expressway_exit' },
    plainMeaning: 'The short ramp that takes you off (or onto) an expressway. Signal early, move to the leftmost lane, then slow down on the ramp, not before.',
    pair: {
      yes: { caption: 'Signalling left early and moving to the exit lane in good time.', scene: { road: 'expressway', lanes: 3, egoLane: 1, signs: [{ id: 'expressway_exit', side: 'left', depth: 0.55 }], markings: ['chevron'], egoIndicator: 'left' } },
      no: { caption: 'Cutting across two lanes at the last moment.', scene: { road: 'expressway', lanes: 3, egoLane: 3, signs: [{ id: 'expressway_exit', side: 'left', depth: 0.3 }], markings: ['chevron'], vehicles: [{ kind: 'car', pos: 'left' }], egoIndicator: 'left' } },
    },
    confusables: ['expressway', 'chevron'],
  },
  {
    id: 'bus_lane',
    name: 'bus lane',
    category: 'marking',
    visual: { sign: 'bus_lane' },
    plainMeaning: 'Lane marked BUS LANE (often with a red surface): reserved for buses during the hours on the sign. Cars may only enter to turn left.',
    confusables: ['one_way', 'keep_left'],
  },
  {
    id: 'no_stopping',
    name: 'no stopping',
    category: 'sign',
    visual: { sign: 'no_stopping' },
    plainMeaning: 'Blue disc, red ring, red cross: you may not stop here at all, not even for a moment.',
    confusables: ['no_waiting', 'double_yellow_zigzag'],
  },
  {
    id: 'no_waiting',
    name: 'no waiting',
    category: 'sign',
    visual: { sign: 'no_waiting' },
    plainMeaning: 'Blue disc, red ring, one red slash: you may stop briefly to drop off or pick up, but not park or wait.',
    confusables: ['no_stopping', 'single_yellow'],
  },
  {
    id: 'road_hump',
    name: 'road hump',
    category: 'sign',
    visual: { sign: 'road_hump' },
    plainMeaning: 'Warning triangle with a bump: a speed hump ahead. Slow down well before it.',
    confusables: ['slippery_road'],
  },
  {
    id: 'slippery_road',
    name: 'slippery road',
    category: 'sign',
    visual: { sign: 'slippery_road' },
    plainMeaning: 'Warning triangle with a skidding car: the surface may be slippery, especially when wet. Ease off and avoid sudden braking.',
    confusables: ['road_hump', 'road_narrows'],
  },
  {
    id: 'road_narrows',
    name: 'road narrows',
    category: 'sign',
    visual: { sign: 'road_narrows' },
    plainMeaning: 'Warning triangle with converging lines: the road gets narrower ahead. Be ready to merge and give way.',
    confusables: ['slippery_road'],
  },
  {
    id: 'school_zone',
    name: 'school zone',
    category: 'sign',
    visual: { sign: 'school_zone' },
    plainMeaning: 'Warning of children near a school. Slow down to 40 km/h and expect people stepping out.',
    confusables: ['pedestrian_crossing_sign'],
  },
  {
    id: 'roundabout',
    name: 'roundabout',
    category: 'place',
    visual: { sign: 'roundabout_ahead' },
    plainMeaning: 'A circular junction you drive around clockwise. Give way to traffic already on it, coming from your right.',
    pair: {
      yes: { caption: 'Waiting for the car on the roundabout coming from the right.', scene: { road: 'roundabout', signs: [{ id: 'roundabout_ahead', side: 'left', depth: 0.3 }], markings: ['give_way_line'], vehicles: [{ kind: 'car', pos: 'cross_right' }] } },
      no: { caption: 'Entering the roundabout in front of that car.', scene: { road: 'roundabout', signs: [{ id: 'roundabout_ahead', side: 'left', depth: 0.3 }], markings: ['give_way_line'], vehicles: [{ kind: 'car', pos: 'cross_right' }], egoIndicator: 'right' } },
    },
    confusables: ['junction', 'give_way'],
  },
  {
    id: 'hazard_lights',
    name: 'hazard lights',
    category: 'vehicle',
    visual: { scene: { road: 'straight', lanes: 2, egoLane: 2, vehicles: [{ kind: 'car', pos: 'ahead', indicator: 'hazard' }] } },
    plainMeaning: 'Both indicators flashing together. Means "I am a hazard": broken down or stopped, not "I am turning".',
    confusables: ['indicator'],
  },
  {
    id: 'indicator',
    name: 'indicator (signal)',
    category: 'vehicle',
    visual: { scene: { road: 'straight', lanes: 2, egoLane: 2, vehicles: [{ kind: 'car', pos: 'ahead', indicator: 'left' }] } },
    plainMeaning: 'The flashing amber light showing which way a vehicle intends to turn or move. Signal early, before you brake or steer.',
    confusables: ['hazard_lights'],
  },
  {
    id: 'emergency_vehicle',
    name: 'emergency vehicle',
    category: 'vehicle',
    visual: { scene: { road: 'straight', lanes: 2, egoLane: 1, vehicles: [{ kind: 'ambulance', pos: 'behind_right', siren: true }] } },
    plainMeaning: 'Ambulance, fire engine or police with siren and flashing lights. Move aside safely and let it pass; never follow closely behind it.',
    confusables: ['hazard_lights'],
  },
  {
    id: 'no_overtaking',
    name: 'no overtaking',
    category: 'sign',
    visual: { sign: 'no_overtaking' },
    plainMeaning: 'Red-ringed circle with two cars, one red: do not overtake on this stretch.',
    confusables: ['overtaking', 'double_white'],
  },
]

export const termById = new Map(terms.map((t) => [t.id, t]))
